### ISSUE TITLE
AccessDeniedException when trying to get GetSecretValue cross-account

### ISSUE THREAD

**Issue by bravogolfgolf** [aws-samples/cdk-assume-role-credential-plugin#49]
I'm modifying the code from this workshop to do cross-account rather than cross-region.

https://cdk-advanced.workshop.aws/start.html

In source stack I try to get a secret value from target account

const myKeyId = SecretValue.secretsManager(<hard-coded full arn of target secret>',{
  jsonField: 'MyKeyID',
}).toString();

I receive this error:
User: arn:aws-us-gov:sts::<source account>:assumed-role/cdk-hnb659fds-cfn-exec-role-<source account>-us-gov-west-1/AWSCloudFormation is not authorized to perform: secretsmanager:GetSecretValue on resource: arn:aws-us-gov:secretsmanager:us-gov-west-1:<target account>:secret:<secret name>-xxxxxx

It seems this scenario is something the plugin was meant to solve.

Is this expected behavior?

**Comment by corymhall** [comment]
The plugin helps when trying to resolve values at `synth` time. The `SecretValue.secretsManager()` method that you are using is for resolving secretsmanager values at `deploy` time (i.e. CloudFormation). That method will return a a CloudFormation [dynamic reference](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html#dynamic-references-secretsmanager) which CloudFormation will resolve. You are getting that error because your CloudFormation execution role does not have access to resolve that value from secretsmanager.

I don't think that secretsmanager has a method that allows you to resolve a value at `synth` time. If the value was not a secret then you could try using parameter store which has a `ssm.StringParameter.valueFromLookup()` method.

**Comment by bravogolfgolf** [comment]
Okay that's good to know.

> You are getting that error because your CloudFormation execution role does not have access to resolve that value from secretsmanager.

Is there a recommended way to change the permissions of these bootstrap roles?

**Comment by corymhall** [comment]
Since it sounds like you are trying to have CloudFormation access a secret from a different AWS account, you will have to add permissions on both the secret side and the CloudFormation side.

1. Update the resource policy for the secret to allow the CloudFormation execution role to get the secret.
2. Update the KMS key policy of the key that is encrypting the secret to allow the CloudFormation execution role to decrypt using the key.
3. Update the CloudFormation execution role to be able to decrypt with the KMS key and get the secret.

This article walks through the relevant IAM policies.
https://aws.amazon.com/premiumsupport/knowledge-center/secrets-manager-share-between-accounts/

In order to update the CloudFormation execution role you will most likely have to customize the bootstrap template. I have an example of how to do that here:
https://github.com/corymhall/cdk-misc-examples/tree/main/example2
